Repository Log234/Mandater, pull requests merged in 2018-05, with the labels that each got.

#105 closes #104 simple change in request link
  Mandater/ClientApp/store/ElectionReducer.ts
Labels: bug

#107 Swagger missing models fix
  Mandater/Controllers/ElectionController.cs
  Mandater/Mandater.csproj
Labels: bug, enhancement

#109 Clean up election reducer
  Mandater/ClientApp/actions/ElectionActionCreator.tsx
  Mandater/ClientApp/actions/ElectionActions.ts
  Mandater/ClientApp/actions/TableActions.tsx
  Mandater/ClientApp/actions/index.ts
  Mandater/ClientApp/components/PresentationComponent.tsx
  Mandater/ClientApp/components/PresentationSelection.tsx
  Mandater/ClientApp/components/TableButton.tsx
  Mandater/ClientApp/constants/index.ts
  Mandater/ClientApp/containers/LayoutContainer.tsx
  Mandater/ClientApp/containers/SettingMenuContainer.tsx
  Mandater/ClientApp/interfaces/AlgorithmPayload.ts
  Mandater/ClientApp/interfaces/SettingsMenuPayload.ts
  Mandater/ClientApp/interfaces/states/ElectionState.ts
  Mandater/ClientApp/logic/AlgorithmUtils.ts
  Mandater/ClientApp/logic/SainteLague.ts
  Mandater/ClientApp/reducers/ElectionReducer.ts
  Mandater/ClientApp/reducers/TableReducer.tsx
  Mandater/ClientApp/reducers/index.ts
  Mandater/ClientApp/states/ElectionState.ts
  Mandater/ClientApp/states/TableState.tsx
  Mandater/ClientApp/states/VisualizationState.tsx
  Mandater/ClientApp/store/ElectionReducer.ts
  Mandater/ClientApp/store/UserInterface.ts
  Mandater/ClientApp/store/index.ts
  Mandater/ClientApp/types/ActionTypes.ts
  Mandater/ClientApp/types/Algorithms.ts
  Mandater/Mandater.csproj
Labels: cleanup

#115 Reset button, smart input box implementation and Reducer overhaul
  Mandater/ClientApp/actions/ComputationActions.ts
  Mandater/ClientApp/actions/ElectionActionCreator.tsx
  Mandater/ClientApp/actions/ElectionActions.ts
  Mandater/ClientApp/actions/RequestedDataActions.ts
  Mandater/ClientApp/actions/SettingActions.ts
  Mandater/ClientApp/components/PresentationComponent.tsx
  Mandater/ClientApp/components/SettingMenuComponent.tsx
  Mandater/ClientApp/components/SmartNumericInput.tsx
  Mandater/ClientApp/containers/LayoutContainer.tsx
  Mandater/ClientApp/containers/PresentationContainer.tsx
  Mandater/ClientApp/containers/SettingMenuContainer.tsx
  Mandater/ClientApp/interfaces/AlgorithmPayload.ts
  Mandater/ClientApp/interfaces/ComputationPayload.ts
  Mandater/ClientApp/interfaces/Election.ts
  Mandater/ClientApp/interfaces/ElectionType.ts
  Mandater/ClientApp/interfaces/PartyResultDictionary.ts
  Mandater/ClientApp/interfaces/SettingsMenuPayload.ts
  Mandater/ClientApp/interfaces/SettingsMenuPlaceholderPayload.ts
  Mandater/ClientApp/interfaces/SettingsPayload.ts
  Mandater/ClientApp/logic/Algorithm.ts
  Mandater/ClientApp/logic/AlgorithmUtils.ts
  Mandater/ClientApp/logic/ApiRequests.ts
  Mandater/ClientApp/logic/SainteLague.ts
  Mandater/ClientApp/logic/Validation.ts
  Mandater/ClientApp/reducers/ComputationReducer.ts
  Mandater/ClientApp/reducers/ElectionReducer.ts
  Mandater/ClientApp/reducers/RequestedDataReducer.ts
  Mandater/ClientApp/reducers/SettingsReducer.ts
  Mandater/ClientApp/states/ComputationState.ts
  Mandater/ClientApp/states/ElectionState.ts
  Mandater/ClientApp/states/RequestedDataState.ts
  Mandater/ClientApp/states/SettingState.ts
  Mandater/ClientApp/store/index.ts
  Mandater/ClientApp/types/ActionTypes.ts
  Mandater/Mandater.csproj
  Mandater/tsconfig.json
Labels: cleanup, enhancement, feature

#117 refactor(front-end): Improve selectionbox value handling
  Mandater/ClientApp/actions/ComputationActions.ts
  Mandater/ClientApp/components/SettingMenuComponent.tsx
  Mandater/ClientApp/containers/SettingMenuContainer.tsx
  Mandater/ClientApp/interfaces/ComputationPayload.ts
  Mandater/ClientApp/logic/SainteLague.ts
  Mandater/ClientApp/reducers/ComputationReducer.ts
  Mandater/ClientApp/states/ComputationState.ts
Labels: cleanup, enhancement

#118 Refactoring
  .gitignore
  Mandater/ClientApp/actions/PresentationActions.tsx
  Mandater/ClientApp/actions/RequestedDataActions.ts
  Mandater/ClientApp/actions/SettingActions.ts
  Mandater/ClientApp/actions/TableActions.tsx
  Mandater/ClientApp/boot-server.tsx
  Mandater/ClientApp/components/Button.tsx
  Mandater/ClientApp/components/LayoutComponent.tsx
  Mandater/ClientApp/components/PresentationComponent.tsx
  Mandater/ClientApp/components/PresentationMenu.tsx
  Mandater/ClientApp/components/PresentationSelection.tsx
  Mandater/ClientApp/components/PresentationSelectionButton.tsx
  Mandater/ClientApp/components/PresentationSettings.tsx
  Mandater/ClientApp/components/SettingMenuComponent.tsx
  Mandater/ClientApp/components/SmartNumericInput.tsx
  Mandater/ClientApp/components/TableButton.tsx
  Mandater/ClientApp/components/TableComponent.tsx
  Mandater/ClientApp/configureStore.ts
  Mandater/ClientApp/containers/LayoutContainer.tsx
  Mandater/ClientApp/containers/PresentationContainer.tsx
  Mandater/ClientApp/containers/PresentationSelectionButtonContainer.tsx
  Mandater/ClientApp/containers/PresentationSettingsContainer.tsx
  Mandater/ClientApp/containers/SettingMenuContainer.tsx
  Mandater/ClientApp/containers/TableButtonContainer.tsx
  Mandater/ClientApp/interfaces/AlgorithmOutput.ts
  Mandater/ClientApp/interfaces/ComputationPayload.ts
  Mandater/ClientApp/interfaces/TableData.ts
  Mandater/ClientApp/logic/AlgorithmUtils.ts
  Mandater/ClientApp/reducers/ComputationReducer.ts
  Mandater/ClientApp/reducers/PresentationReducer.tsx
  Mandater/ClientApp/reducers/RequestedDataReducer.ts
  Mandater/ClientApp/reducers/SettingsReducer.ts
  Mandater/ClientApp/reducers/TableReducer.tsx
  Mandater/ClientApp/states/ComputationState.ts
  Mandater/ClientApp/states/PresentationState.tsx
  Mandater/ClientApp/states/RequestedDataState.ts
  Mandater/ClientApp/states/SettingState.ts
  Mandater/ClientApp/states/TableState.tsx
  Mandater/ClientApp/store/index.ts
  Mandater/ClientApp/types/ActionTypes.ts
  Mandater/ClientApp/types/AlgorithmType.ts
  Mandater/ClientApp/types/PresentationType.ts
  Mandater/Mandater.csproj
  Mandater/npm-shrinkwrap.json
  Mandater/webpack.config.js
  Mandater/webpack.config.vendor.js
Labels: cleanup, enhancement, feature
